export const URLS = {
    DOMEN: 'https://kitapal.kz/api/',
    API: {
      MAIN: 'main',
      GENRE: 'genre',
      AUTH: {
        LOGIN: 'login',
        REGISTER: 'register',
        FORGOT_PASSWORD: 'forgot_password',
      },
      PROFILE: 'profile',
      UPDATE_PROFILE: 'updateProfile',
      GET_BOOK: 'getBook',
      ARTICLE: 'article',
      AUTHOR: 'author',
      PUBLISHER: 'publisher',
      GET_CATOLOG_BOOKS: 'getCatalogBooks',
      SEARCH: 'search',
      BASKET: 'basket',
      ADD_BASKET: 'addtobasket',
      ORDER: 'order',
      MY_BOOKS: 'myBooks',
      BOOK_CHAPTER: 'book/chapters',
      NAVIGATION: 'navigation',
      SUBSCRIPTION: 'subscriptions',
      PAGE: 'page',
      HISTORY: 'shoppingHistory',
      SELECTED: 'selected',
      ADD_SELECTED: 'add-selected',
      LEAVE_FEEDBACK: 'leaveFeedback',
      USER_SUBSCRIPTION: 'user-subscription',
      USER_ALL_ORDERS: 'user-all-orders',
      OPENED_SUB_BOOK: 'opened-subscription-book',
      SINGLE_SUBSCRIPTION: 'subscription',
      PAYMENT_INIT: 'paymentinit',
      SOCIAL_AUTH: 'social-auth',
      STORE_TOKEN: 'store-token',
      USER_READING_BOOK: 'user-reading-book',
      USER_FINISHED_BOOK: 'user-finished-book',
      GIFT_PAGE: 'giftpage',
      GET_OS: 'getos2',
      CHECK_PROMO: 'checkPromo',
    },
  };